const types = {
  IMAGES_FETCH_REQUESTED: "GALLERY/IMAGES_FETCH_REQUESTED",
  IMAGES_FETCH_PENDING: "GALLERY/IMAGES_FETCH_PENDING",
  IMAGES_FETCH_SUCCEEDED: "GALLERY/IMAGES_FETCH_SUCCEEDED",
  IMAGES_FETCH_FAILED: "GALLERY/IMAGES_FETCH_FAILED"
};
export default types;
